module.exports = {
  url: 'localhost:3000',
  elements: {
    title: '.titleBar',
    valid: '#validHeader',
    invalid: 'span[name="queryTitle"]',
    burger: '.bm-burger-button',
    enterWanted: 'p[name="enterOption"]',
    modifyWanted: 'p[name="modifyOption"]',
    cancelWanted: 'p[name="cancelOption"]',
    reasonForCancellation: 'input[name="resInput"]',
    dateOfCancel: 'input[name="datInput"]',
    warrantID: 'input[name="widInput"]',
    header: 'input[name="hdrInput"]',
    mke: 'input[name="mkeInput"]',
    agency: 'input[name="oriInput"]',
    name: 'input[name="namInput"]',
    sex: 'select[name="sexInput"]',
    race: 'select[name="racInput"]',
    height: 'input[name="hgtInput"]',
    weight: 'input[name="wgtInput"]',
    hairColor: 'input[name="haiInput"]',
    offense: 'input[name="offInput"]',
    dateOfWarrant: 'input[name="dowInput"]',
    operatorLicense: 'input[name="olnInput"]',
    olState: 'input[name="olsInput"]',
    olExpiration: 'input[name="oldInput"]',
    licensePlate: 'input[name="licInput"]',
    plateState: 'input[name="lisInput"]',
    plateYear: 'input[name="lidInput"]',
    submit: '#saveBtn',
    clear: '#clearBtn',
    queryBody: 'span[name="queryBody"]'
  }
}
